name: TOREBO
favicon: null
layout_spectrum: 0.51891
typography_spectrum: 0.54902
title: Salvatore Bongiorno
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#3b3b3b'
    - '#7e7e7e'
    - '#bebebe'
    - '#fefefe'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
