name: TOREBO
favicon: null
layout_spectrum: 0.99185
typography_spectrum: 0.58894
title: Salvatore Bongiorno
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebedea'
    - '#281315'
    - '#d2cad1'
    - '#8f8286'
    - '#9f2a2c'
  brandStrength: 0.3125
  lightness: 0
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
